services:
  - type: web
    name: barge2rail-sso
    runtime: docker
    region: ohio  # Columbus region
    plan: starter
    healthCheckPath: /api/auth/health/  # Fixed: matches your Django endpoint
    # CRITICAL: Django WSGI start command
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"  # String format for environment variables
      - key: BASE_URL
        value: "https://sso.barge2rail.com"  # Fixed: explicit value instead of dynamic
      - key: ALLOWED_HOSTS
        value: "sso.barge2rail.com,barge2rail-sso.onrender.com"  # Include both custom domain and Render URL
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://sso.barge2rail.com"  # Fixed: include https:// prefix
      - key: GOOGLE_CLIENT_ID
        sync: false  # You'll set these manually in Render dashboard
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: "https://sso.barge2rail.com,http://localhost:3000,http://localhost:8000,http://127.0.0.1:8000"
