services:
  - type: web
    name: barge2rail-sso
    runtime: docker
    region: oregon
    plan: starter
    healthCheckPath: /health/
    envVars:
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        fromService:
          type: web
          name: barge2rail-sso
          property: hostnames
      - key: CSRF_TRUSTED_ORIGINS
        fromService:
          type: web
          name: barge2rail-sso
          property: hostnames
      - key: BASE_URL
        fromService:
          type: web
          name: barge2rail-sso
          property: hostnames
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false