services:
  - type: web
    name: barge2rail-sso
    runtime: docker
    region: ohio  # Columbus region
    plan: starter
    healthCheckPath: /api/auth/health/
    
    envVars:
      # CRITICAL: Security settings
      - key: SECRET_KEY
        generateValue: true  # Render will generate a secure key
      
      # CRITICAL: Neon PostgreSQL Database
      # You'll paste your Neon connection string in Render dashboard
      - key: DATABASE_URL
        sync: false  # Set manually in Render dashboard with your Neon connection string
      
      # Django settings
      - key: DEBUG
        value: "False"
      - key: BASE_URL
        value: "https://sso.barge2rail.com"
      - key: ALLOWED_HOSTS
        value: "sso.barge2rail.com,barge2rail-sso.onrender.com,*.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://sso.barge2rail.com,https://barge2rail-sso.onrender.com"
      
      # Google OAuth (set manually in Render dashboard)
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      
      # CORS configuration
      - key: CORS_ALLOWED_ORIGINS
        value: "https://sso.barge2rail.com,https://admin.barge2rail.com,https://barge2rail-sso.onrender.com,http://localhost:3000,http://localhost:8000"
      
      # Logging
      - key: DJANGO_LOG_LEVEL
        value: "INFO"
      
      # Optional: Admin user creation on first deploy
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false  # Set if you want auto-creation
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false  # Set if you want auto-creation

# No databases section needed - using external Neon PostgreSQL
