# Generated by Django 4.2.24 on 2025-10-01 18:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profiel",
            new_name="Profile",
        ),
    ]
