# Generated by Django 4.2.24 on 2025-09-21 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0002_application_slug_user_anonymous_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(choices=[('primetrade', 'PrimeTrade'), ('database', 'Customer Database'), ('repair', 'Repair Ticketing'), ('barge', 'Barge Tracking'), ('admin', 'Admin Dashboard')], max_length=50)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('user', 'Standard User'), ('viewer', 'Read Only'), ('operator', 'Operator')], max_length=50)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Role',
                'verbose_name_plural': 'Application Roles',
                'db_table': 'sso_application_roles',
                'unique_together': {('user', 'application')},
            },
        ),
    ]
