# Generated by Django 4.2.24 on 2025-10-04 21:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0003_applicationrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenExchangeSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('user_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sso_token_exchange_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expires_at', 'used'], name='sso_token_e_expires_1d37a2_idx')],
            },
        ),
    ]
