# Generated by Django 4.2.24 on 2025-10-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0004_tokenexchangesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sso_login_attempts',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['identifier', 'attempted_at'], name='sso_login_a_identif_5f7053_idx'), models.Index(fields=['ip_address', 'attempted_at'], name='sso_login_a_ip_addr_99120f_idx')],
            },
        ),
    ]
