# Generated by Django 4.2.24 on 2025-10-10 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0006_alter_application_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=128, unique=True)),
                ('redirect_uri', models.URLField()),
                ('scope', models.CharField(default='openid email profile', max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_codes', to='sso.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sso_authorization_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code', 'used'], name='sso_authori_code_09faf0_idx')],
            },
        ),
    ]
