# Generated by Django 4.2.24 on 2025-10-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0007_authorizationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_method',
            field=models.CharField(choices=[('google', 'Google OAuth'), ('password', 'Password Authentication')], default='password', help_text='How this user authenticates', max_length=20),
        ),
    ]
