# Generated by Django 4.2.24 on 2025-10-27 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sso", "0008_user_auth_method"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="updated_at",
            new_name="updated",
        ),
        migrations.AddField(
            model_name="application",
            name="algorithm",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No OIDC support"),
                    ("RS256", "RSA with SHA-2 256"),
                    ("HS256", "HMAC with SHA-2 256"),
                ],
                default="",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="allowed_origins",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Allowed origins list to enable CORS, space separated",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="authorization_grant_type",
            field=models.CharField(
                choices=[
                    ("authorization-code", "Authorization code"),
                    ("implicit", "Implicit"),
                    ("password", "Resource owner password-based"),
                    ("client-credentials", "Client credentials"),
                    ("openid-hybrid", "OpenID connect hybrid"),
                ],
                default="authorization-code",
                help_text="OAuth2 grant type for this application",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="client_type",
            field=models.CharField(
                choices=[("confidential", "Confidential"), ("public", "Public")],
                default="confidential",
                help_text="Confidential clients can keep secrets, public clients cannot",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="hash_client_secret",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="application",
            name="post_logout_redirect_uris",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Allowed Post Logout URIs list, space separated",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="skip_authorization",
            field=models.BooleanField(
                default=False,
                help_text="Skip authorization screen for trusted applications",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this application (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="oauth_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="client_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Auto-generated if left blank. Format: app_XXXXXXXXXXXXXXXX",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="redirect_uris",
            field=models.TextField(
                blank=True,
                help_text="Comma or newline-separated list of allowed redirect URIs",
            ),
        ),
    ]
