# Generated by Django 4.2.24 on 2025-11-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sso", "0010_set_rs256_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="pin_code",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
