# Generated by Django 4.2.24 on 2025-11-07 12:50

from django.db import migrations


def fix_empty_usernames(apps, schema_editor):
    """
    Fix existing users with empty usernames.

    Logic:
    - If user has email and auth_type is 'email' or 'google': username = email
    - If user is anonymous or auth_type is 'anonymous': generate Guest-XXXXXX username
    - Otherwise: generate uuid-based username
    """
    User = apps.get_model("sso", "User")

    users_to_update = User.objects.filter(username="") | User.objects.filter(
        username__isnull=True
    )

    fixed_count = 0
    for user in users_to_update:
        if user.email and user.auth_type in ["email", "google"]:
            # Use email as username
            user.username = user.email
            fixed_count += 1
        elif user.auth_type == "anonymous" or user.is_anonymous:
            # Generate anonymous username if not exists
            if not user.anonymous_username:
                # Generate Guest-XXXXXX username
                import random
                import string

                suffix = "".join(
                    random.choices(string.ascii_uppercase + string.digits, k=6)
                )
                user.anonymous_username = f"Guest-{suffix}"

            user.username = user.anonymous_username
            fixed_count += 1
        elif user.email:
            # Has email but no specific auth_type, use email
            user.username = user.email
            fixed_count += 1
        else:
            # No email, generate UUID-based username
            user.username = f"legacy_{user.id}"
            fixed_count += 1

        user.save(update_fields=["username", "anonymous_username"])

    print(f"Fixed {fixed_count} users with empty usernames")


class Migration(migrations.Migration):

    dependencies = [
        ("sso", "0012_passwordresettoken"),
    ]

    operations = [
        migrations.RunPython(
            fix_empty_usernames, reverse_code=migrations.RunPython.noop
        ),
    ]
