# Generated by Django 4.2.24 on 2025-11-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sso", "0013_fix_empty_usernames"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="applicationrole",
            name="permissions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Auto-assigned based on role. "
                    "Can be manually overridden if needed."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="applicationrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Office", "Office"),
                    ("Client", "Client"),
                ],
                help_text=(
                    "User's role for this application " "(permissions auto-assigned)"
                ),
                max_length=50,
            ),
        ),
    ]
