# Generated by Django 4.2.24 on 2025-11-07 18:48

from django.db import migrations


def add_primetrade_post_logout_uris(apps, schema_editor):
    """Add post-logout redirect URIs to PrimeTrade application for OIDC logout flow"""
    Application = apps.get_model("sso", "Application")

    try:
        app = Application.objects.get(name="PrimeTrade")
        app.post_logout_redirect_uris = """http://localhost:8001/auth/login/
http://127.0.0.1:8001/auth/login/
https://prt.barge2rail.com/auth/login/"""
        app.save()
        print("✅ Added post-logout redirect URIs to PrimeTrade application")
    except Application.DoesNotExist:
        print(
            "⚠️  PrimeTrade application not found, "
            "skipping post-logout URI configuration"
        )


def remove_primetrade_post_logout_uris(apps, schema_editor):
    """Remove post-logout redirect URIs from PrimeTrade application"""
    Application = apps.get_model("sso", "Application")

    try:
        app = Application.objects.get(name="PrimeTrade")
        app.post_logout_redirect_uris = ""
        app.save()
        print("✅ Removed post-logout redirect URIs from PrimeTrade application")
    except Application.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("sso", "0014_three_role_system"),
    ]

    operations = [
        migrations.RunPython(
            add_primetrade_post_logout_uris, remove_primetrade_post_logout_uris
        ),
    ]
