# Generated by Django 4.2.24 on 2025-11-07 18:56

from django.db import migrations


def configure_post_logout_uris(apps, schema_editor):
    """
    Ensure PrimeTrade post-logout redirect URIs include all environments.

    Each application's post-logout URIs should match their callback URIs
    to ensure users return to the correct application after SSO logout.

    For future apps: Add them to the configs list with their URIs.
    """
    Application = apps.get_model("sso", "Application")

    # Only PrimeTrade is currently connected
    configs = [
        (
            "PrimeTrade",
            """http://localhost:8001/auth/login/
http://127.0.0.1:8001/auth/login/
https://prt.barge2rail.com/auth/login/
https://django-primetrade.onrender.com/auth/login/""",
        ),
    ]

    for app_name, post_logout_uris in configs:
        try:
            app = Application.objects.get(name=app_name)
            app.post_logout_redirect_uris = post_logout_uris
            app.save()
            print(f"✅ Configured post-logout URIs for {app_name}")
        except Application.DoesNotExist:
            print(f"⚠️  {app_name} not found, skipping")


def remove_post_logout_uris(apps, schema_editor):
    """Remove post-logout redirect URIs from all applications"""
    Application = apps.get_model("sso", "Application")

    for app in Application.objects.all():
        app.post_logout_redirect_uris = ""
        app.save()


class Migration(migrations.Migration):

    dependencies = [
        ("sso", "0015_add_primetrade_post_logout_uris"),
    ]

    operations = [
        migrations.RunPython(configure_post_logout_uris, remove_post_logout_uris),
    ]
