# Generated by Django 4.2.24 on 2025-11-07 19:33

from django.db import migrations


def add_jrose_admin(apps, schema_editor):
    """Add jrose@barge2rail.com with PrimeTrade Admin privileges"""
    User = apps.get_model("sso", "User")
    ApplicationRole = apps.get_model("sso", "ApplicationRole")

    # Create or get the user
    user, created = User.objects.get_or_create(
        email="jrose@barge2rail.com",
        defaults={
            "username": "jrose@barge2rail.com",
            "is_staff": True,
            "is_sso_admin": True,
        },
    )

    if created:
        print("✅ Created user: jrose@barge2rail.com")
    else:
        print("ℹ️  User already exists: jrose@barge2rail.com")

    # Grant PrimeTrade Admin role
    role, created = ApplicationRole.objects.get_or_create(
        user=user,
        application="primetrade",
        defaults={"role": "Admin", "permissions": ["full_access"]},
    )

    if created:
        print("✅ Granted PrimeTrade Admin role to jrose@barge2rail.com")
    else:
        print(f"ℹ️  jrose@barge2rail.com already has PrimeTrade role: {role.role}")


def remove_jrose_admin(apps, schema_editor):
    """Remove jrose@barge2rail.com and their roles"""
    User = apps.get_model("sso", "User")
    ApplicationRole = apps.get_model("sso", "ApplicationRole")

    try:
        user = User.objects.get(email="jrose@barge2rail.com")
        ApplicationRole.objects.filter(user=user).delete()
        user.delete()
        print("✅ Removed jrose@barge2rail.com")
    except User.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("sso", "0016_configure_all_post_logout_uris"),
    ]

    operations = [
        migrations.RunPython(add_jrose_admin, remove_jrose_admin),
    ]
