# Generated by Django 5.2.8 on 2025-11-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sso", "0017_add_jrose_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="pin_code",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
