# Generated by Django 4.2.24 on 2025-11-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sso", "0018_alter_user_pin_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="pin_code",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
