# Generated by Django 4.2.24 on 2025-11-28 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sso", "0019_hash_pin_code_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationrole",
            name="application_new",
            field=models.ForeignKey(
                blank=True,
                help_text="New FK field - will replace CharField application",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="sso.application",
            ),
        ),
        migrations.AlterField(
            model_name="applicationrole",
            name="application",
            field=models.CharField(
                choices=[
                    ("primetrade", "PrimeTrade"),
                    ("sacks", "Sacks Inventory System"),
                    ("database", "Customer Database"),
                    ("repair", "Repair Ticketing"),
                    ("barge", "Barge Tracking"),
                    ("admin", "Admin Dashboard"),
                ],
                max_length=50,
            ),
        ),
    ]
