# Generated by Django 4.2.24 on 2025-11-28 17:22

from django.db import migrations


def migrate_application_data(apps, schema_editor):
    """
    Migrate ApplicationRole.application from CharField to ForeignKey.

    Match CharField values to Application.slug:
    - "primetrade" → Application(slug="primetrade")
    - "sacks" → Application(slug="sacks")
    - Delete orphan roles (database, repair, barge, admin)
      that don't have matching Applications
    """
    ApplicationRole = apps.get_model("sso", "ApplicationRole")
    Application = apps.get_model("sso", "Application")

    orphan_count = 0
    migrated_count = 0

    for role in ApplicationRole.objects.all():
        slug = role.application  # CharField value

        try:
            app = Application.objects.get(slug=slug)
            role.application_new = app
            role.save()
            migrated_count += 1
            print(f"✓ Migrated role: {role.user.email} → {app.name}")
        except Application.DoesNotExist:
            print(
                f"✗ Deleting orphan role: {role.user.email} → {slug} "
                f"(no matching Application)"
            )
            role.delete()
            orphan_count += 1

    print(
        f"\nMigration complete: {migrated_count} migrated, "
        f"{orphan_count} orphans deleted"
    )


def reverse_migration(apps, schema_editor):
    """
    Reverse: Copy application_new back to application CharField.
    Note: This will fail if there are orphan roles that were deleted.
    """
    ApplicationRole = apps.get_model("sso", "ApplicationRole")

    for role in ApplicationRole.objects.all():
        if role.application_new:
            role.application = role.application_new.slug
            role.save()


class Migration(migrations.Migration):

    dependencies = [
        ("sso", "0020_add_application_fk"),
    ]

    operations = [
        migrations.RunPython(migrate_application_data, reverse_migration),
    ]
