# Generated by Django 4.2.24 on 2025-12-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sso", "0022_replace_application_charfield_with_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="force_pin_change",
            field=models.BooleanField(
                default=True, help_text="User must set their own PIN on first login"
            ),
        ),
    ]
