# Generated by Django 4.2.24 on 2025-12-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sso", "0024_add_operator_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Office", "Office"),
                    ("Operator", "Operator"),
                    ("Client", "Client"),
                ],
                help_text="User's role for this application (permissions auto-assigned)",
                max_length=50,
            ),
        ),
    ]
