# Generated by Django 4.2.24 on 2025-12-05 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sso", "0025_alter_applicationrole_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Machine-readable code (e.g., 'bol', 'releases', 'schedule')",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name (e.g., 'Bill of Lading', 'Releases')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this feature"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive features won't be included in JWT claims",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for display in admin UI"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        help_text="Application this feature belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="sso.application",
                    ),
                ),
            ],
            options={
                "db_table": "sso_features",
                "ordering": ["application", "display_order", "code"],
                "unique_together": {("application", "code")},
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Machine-readable code (e.g., 'view', 'create', 'modify', 'delete')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name (e.g., 'View', 'Create', 'Modify', 'Delete')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this permission allows",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for display in admin UI"
                    ),
                ),
            ],
            options={
                "db_table": "sso_permissions",
                "ordering": ["display_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Machine-readable code (e.g., 'primetrade_admin', 'senco_viewer')",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name (e.g., 'PrimeTrade Admin', 'Senco Viewer')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of this role's purpose and access level",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive roles cannot be assigned to users",
                    ),
                ),
                (
                    "legacy_role",
                    models.CharField(
                        blank=True,
                        help_text="Legacy role code for backward compatibility (Admin/Office/Operator/Client)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        help_text="Application this role belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_roles",
                        to="sso.application",
                    ),
                ),
            ],
            options={
                "db_table": "sso_roles",
                "ordering": ["application", "name"],
                "unique_together": {("application", "code")},
            },
        ),
        migrations.CreateModel(
            name="UserAppRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_code",
                    models.CharField(
                        blank=True,
                        help_text="Tenant code for multi-tenant apps (e.g., 'LIBERTY', 'SENCO')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Inactive assignments are ignored"
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes about this assignment"
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made this assignment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        help_text="Role assigned to this user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="sso.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sso_user_app_roles",
                "ordering": ["user", "role", "tenant_code"],
            },
        ),
        migrations.CreateModel(
            name="RoleFeaturePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="sso.feature",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_feature_permissions",
                        to="sso.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_permissions",
                        to="sso.role",
                    ),
                ),
            ],
            options={
                "db_table": "sso_role_feature_permissions",
                "ordering": ["role", "feature", "permission"],
                "unique_together": {("role", "feature", "permission")},
            },
        ),
    ]
