# Generated by Django 5.2.8 on 2026-01-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sso", "0027_rbac_audit_trail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code (e.g., HLR, GNP, TRX)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., Hiller Carbon)", max_length=100
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive tenants won't appear in dropdowns",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sso_tenants",
                "ordering": ["code"],
            },
        ),
        migrations.AlterField(
            model_name="historicalrole",
            name="code",
            field=models.CharField(
                help_text="Machine-readable code (e.g., 'primetrade_admin')",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrole",
            name="name",
            field=models.CharField(
                help_text="Human-readable name (e.g., 'PrimeTrade Admin')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="historicaluserapprole",
            name="tenant_code",
            field=models.CharField(
                blank=True,
                help_text="Tenant code for multi-tenant apps (e.g., 'LIBERTY')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="legacy_role",
            field=models.CharField(
                blank=True,
                help_text="Legacy role code for backward compatibility",
                max_length=50,
            ),
        ),
    ]
