# Generated by Django 5.2.8 on 2026-01-08 18:52

from django.db import migrations


def seed_tenants(apps, schema_editor):
    """Seed initial tenant codes for role assignment dropdowns."""
    Tenant = apps.get_model("sso", "Tenant")
    tenants_data = [
        ("GNP", "GNP Commodities"),
        ("HLR", "Hiller Carbon"),
        ("TRX", "Traxys"),
        ("YAS", "Yasuda"),
        ("YFN", "Yifan"),
    ]
    for code, name in tenants_data:
        Tenant.objects.get_or_create(code=code, defaults={"name": name})


def reverse_seed(apps, schema_editor):
    """Remove seeded tenants (optional - keeps data on reverse)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("sso", "0028_add_tenant_model"),
    ]

    operations = [
        migrations.RunPython(seed_tenants, reverse_seed),
    ]
