# Generated by Django 4.2.24 on 2025-09-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Supersacs', 'Supersacs'), ('Metals', 'Metals'), ('Misc', 'Misc')], max_length=20, null=True)),
                ('quantity', models.PositiveBigIntegerField(null=True)),
            ],
        ),
    ]
