# Generated by Django 4.2.24 on 2025-09-26 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_product_quantity_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name_plural": "Order"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name_plural": "Product"},
        ),
    ]
