# Generated by Django 4.2.24 on 2025-10-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_remove_product_category_product_extra_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="extra_data",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Supersacs", "Supersacs"),
                    ("Metals", "Metals"),
                    ("Misc", "Misc"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
