# Generated by Django 4.2.24 on 2025-10-17 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0009_rawproductdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillOfLadingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_file",
                    models.FileField(
                        help_text="Upload template file (PDF, DOCX, or HTML)",
                        upload_to="bol_templates/",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional notes about this template"
                    ),
                ),
                (
                    "supplier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bol_template",
                        to="dashboard.supplier",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill of Lading Template",
                "verbose_name_plural": "Bill of Lading Templates",
                "ordering": ["supplier__name"],
            },
        ),
    ]
