# Generated by Django 4.2.24 on 2025-10-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_billofladingtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofladingtemplate',
            name='field_mapping',
            field=models.JSONField(blank=True, help_text='Field mapping for spreadsheet templates (JSON)', null=True),
        ),
        migrations.AddField(
            model_name='billofladingtemplate',
            name='template_type',
            field=models.CharField(blank=True, help_text='Type of template: document or spreadsheet', max_length=20),
        ),
        migrations.AlterField(
            model_name='billofladingtemplate',
            name='template_file',
            field=models.FileField(help_text='Upload template file (PDF, DOCX, HTML, CSV, or XLSX)', upload_to='bol_templates/'),
        ),
    ]
