# Generated by Django 4.2.24 on 2025-10-17 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0011_billofladingtemplate_field_mapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfLading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=50, unique=True)),
                ('shipper_name', models.CharField(blank=True, max_length=255)),
                ('shipper_address', models.TextField(blank=True)),
                ('consignee_name', models.CharField(blank=True, max_length=255)),
                ('consignee_address', models.TextField(blank=True)),
                ('origin', models.CharField(blank=True, max_length=255)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('carrier', models.CharField(blank=True, max_length=255)),
                ('vessel_name', models.CharField(blank=True, max_length=255)),
                ('container_number', models.CharField(blank=True, max_length=100)),
                ('seal_number', models.CharField(blank=True, max_length=100)),
                ('freight_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, help_text='Expected delivery date', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='generated_bols/')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bols', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.supplier')),
            ],
            options={
                'verbose_name_plural': 'Bills of Lading',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='billofladingtemplate',
            options={'ordering': ['-uploaded_at'], 'verbose_name_plural': 'Bill of Lading Templates'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Order'},
        ),
        migrations.RemoveField(
            model_name='billofladingtemplate',
            name='field_mapping',
        ),
        migrations.RemoveField(
            model_name='billofladingtemplate',
            name='template_type',
        ),
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Scheduled delivery date', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in lbs', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='billofladingtemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='billofladingtemplate',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='billofladingtemplate',
            name='template_file',
            field=models.FileField(upload_to='bol_templates/'),
        ),
        migrations.CreateModel(
            name='BillOfLadingLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('bill_of_lading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='dashboard.billoflading')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.product')),
            ],
            options={
                'verbose_name_plural': 'Bill of Lading Line Items',
            },
        ),
        migrations.AddField(
            model_name='billoflading',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.billofladingtemplate'),
        ),
        migrations.AddField(
            model_name='order',
            name='bill_of_lading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='dashboard.billoflading'),
        ),
    ]
