# Generated by Django 4.2.24 on 2025-10-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_billoflading_alter_billofladingtemplate_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billofladingtemplate",
            name="field_mapping",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Extracted field structure from template PDF for quick BOL creation",
            ),
        ),
        migrations.AddField(
            model_name="billofladingtemplate",
            name="is_configured",
            field=models.BooleanField(
                default=False,
                help_text="Whether field mapping has been extracted and configured",
            ),
        ),
    ]
