# Generated by Django 4.2.7 on 2025-10-29 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_add_field_mapping_to_bol_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billoflading',
            name='template',
        ),
        migrations.DeleteModel(
            name='BillOfLadingTemplate',
        ),
    ]
