# Generated by Django 4.2.7 on 2025-11-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_trailer_number_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='billoflading',
            name='truck_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
