# Generated by Django 4.2.7 on 2025-10-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_bol_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billoflading',
            name='freight_charges',
        ),
    ]
