# Generated by Django 4.2.7 on 2025-10-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_freight_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='billoflading',
            name='truck_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
