# Generated by Django 4.2.7 on 2025-11-07 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_billoflading_truck_number'),
    ]

    operations = [
    ]
