# Generated by Django 4.2.7 on 2025-11-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20251107_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofladinglineitem',
            name='po_number',
            field=models.CharField(blank=True, help_text='Purchase Order number', max_length=100, null=True),
        ),
    ]
