# Generated by Django 4.2.7 on 2025-11-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_billofladinglineitem_po_number'),
    ]

    operations = [
    ]
