# Generated by Django 4.2.7 on 2025-11-07 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_fix_po_number_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billoflading',
            name='template',
        ),
        migrations.DeleteModel(
            name='BillOfLadingTemplate',
        ),
    ]
